version: "3.8"

services:
  interseguro-operations:
    build:
      context: ./interseguro-operations
      dockerfile: Dockerfile
    container_name: interseguro-operations
    ports:
      - "3001:3001"
    networks:
      - interseguro-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3001/",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  interseguro-qr:
    build:
      context: ./interseguro-qr
      dockerfile: Dockerfile
    container_name: interseguro-qr
    ports:
      - "3000:3000"
    networks:
      - interseguro-network
    environment:
      - MATRIX_API_URL=http://interseguro-operations:3001
    depends_on:
      interseguro-operations:
        condition: service_healthy

networks:
  interseguro-network:
    driver: bridge
